// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';`
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSzRQ5p5bIsR4cAwA0KadomfiVSk-zQJQ',
    appId: '1:586775190474:web:fae4892460ebd5ad554d33',
    messagingSenderId: '586775190474',
    projectId: 'waddecar-cleaning-log',
    authDomain: 'waddecar-cleaning-log.firebaseapp.com',
    storageBucket: 'waddecar-cleaning-log.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDStMAKcYKoxD2Im_5qTpaCIA3tOETvf-c',
    appId: '1:586775190474:android:69d683663678612a554d33',
    messagingSenderId: '586775190474',
    projectId: 'waddecar-cleaning-log',
    storageBucket: 'waddecar-cleaning-log.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqai4L8xYLrz7Mf5LWBv2ite9ei4tlYPc',
    appId: '1:586775190474:ios:722d45f7e0803cc9554d33',
    messagingSenderId: '586775190474',
    projectId: 'waddecar-cleaning-log',
    storageBucket: 'waddecar-cleaning-log.firebasestorage.app',
    iosBundleId: 'com.example.waddecarCleaningLog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqai4L8xYLrz7Mf5LWBv2ite9ei4tlYPc',
    appId: '1:586775190474:ios:722d45f7e0803cc9554d33',
    messagingSenderId: '586775190474',
    projectId: 'waddecar-cleaning-log',
    storageBucket: 'waddecar-cleaning-log.firebasestorage.app',
    iosBundleId: 'com.example.waddecarCleaningLog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSzRQ5p5bIsR4cAwA0KadomfiVSk-zQJQ',
    appId: '1:586775190474:web:e52f34bcac4974c7554d33',
    messagingSenderId: '586775190474',
    projectId: 'waddecar-cleaning-log',
    authDomain: 'waddecar-cleaning-log.firebaseapp.com',
    storageBucket: 'waddecar-cleaning-log.firebasestorage.app',
  );
}
